// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiIKKw0VZYuUbRaxfrnNpggRlDlJlkwA',
    appId: '1:851581617516:web:d9f4dcdb0381dbdaac1f49',
    messagingSenderId: '851581617516',
    projectId: 'boardinghousemanagement-2ba24',
    authDomain: 'boardinghousemanagement-2ba24.firebaseapp.com',
    storageBucket: 'boardinghousemanagement-2ba24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTVK0NpiRif1a7G1die0StODIJYpWSFs',
    appId: '1:851581617516:android:b98bf1e42d52f532ac1f49',
    messagingSenderId: '851581617516',
    projectId: 'boardinghousemanagement-2ba24',
    storageBucket: 'boardinghousemanagement-2ba24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA170EJilanaYYyMFZhmI2Oq4pe6Avhfak',
    appId: '1:851581617516:ios:f154c281ce3e4e4eac1f49',
    messagingSenderId: '851581617516',
    projectId: 'boardinghousemanagement-2ba24',
    storageBucket: 'boardinghousemanagement-2ba24.appspot.com',
    iosBundleId: 'com.example.boardingHouseManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA170EJilanaYYyMFZhmI2Oq4pe6Avhfak',
    appId: '1:851581617516:ios:f154c281ce3e4e4eac1f49',
    messagingSenderId: '851581617516',
    projectId: 'boardinghousemanagement-2ba24',
    storageBucket: 'boardinghousemanagement-2ba24.appspot.com',
    iosBundleId: 'com.example.boardingHouseManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmiIKKw0VZYuUbRaxfrnNpggRlDlJlkwA',
    appId: '1:851581617516:web:f95ed50c84e2603fac1f49',
    messagingSenderId: '851581617516',
    projectId: 'boardinghousemanagement-2ba24',
    authDomain: 'boardinghousemanagement-2ba24.firebaseapp.com',
    storageBucket: 'boardinghousemanagement-2ba24.appspot.com',
  );
}
